//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dps.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int ExaminationId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Waist { get; set; }
        public Nullable<double> Glucose { get; set; }
        public Nullable<double> Cholesterol { get; set; }
        public Nullable<int> SBPla { get; set; }
        public Nullable<int> SBPra { get; set; }
        public Nullable<int> SBPll { get; set; }
        public Nullable<int> SBPrl { get; set; }
        public Nullable<int> DBPla { get; set; }
        public Nullable<int> DBPra { get; set; }
        public Nullable<int> DBPll { get; set; }
        public Nullable<int> DBPrl { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<double> cfPWV { get; set; }
        public Nullable<double> baPWV { get; set; }
    }
}
